### ISSUE TITLE
Clarification: How should inventory item count of the same type of item be stored?

### ISSUE THREAD

**Issue by nymann** [projektgruppe18/WorldOfJunk#19]
Right now the amount of a certain item is stored within the item itself, to me this is wrong.

Instead I propose the following ideas (which all of them have Inventory as it's own class):

* In the Inventory class we have an array list of type Item (called items). And if the same item is occurring 5 times for example within the inventory we simply have that item 5 times in the inventory ArrayList.

* Within the Inventory class we have a HashMap of HashMap<String (inventory item name), InventoryItem>. InventoryItem has two variables, amount and item. By doing it this way it's more performant when making operations on the inventory.

**Comment by Mauge9638** [comment]
As of right now i would go for option 1, due to the simple reason that we haven't been taught about HashMaps yet, but if it's something you think we could get taught kinda fast, i don't see any problem in going with that.

**Comment by nymann** [comment]
A HashMap is the same as a dictionary, fx:

{
  "key": value
}

a key has to be unique, so here the structure would look like this:

{
    "Cola": InventoryItem,
    "Bread Sticks": InventoryItem,
    "Cheese": InventoryItem
}

Where an InventoryItem has information about amount (stacksize) and the Item.
Item being:
name,
and then some stats like:
calories,
weight,

 etc.

**Comment by Mauge9638** [comment]
Seems fine to me :)
